xcodeproj 'iosFramework.xcodeproj'

target 'iosFramework' do
	platform:ios, '7.1'
	pod 'FMDB'
	pod 'MWFeedParser'
end

if defined? installer_representation.project
    installer_representation.project.targets.each do |target|
         target.build_configurations.each do |config|
                config.build_settings[‘ONLY_ACTIVE_ARCH’] = ‘NO’
         end
	end
end

if defined? installer_representation.pods_project
    installer_representation.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
                config.build_settings[‘ONLY_ACTIVE_ARCH’] = ‘NO’
         end
	end
end
